### ISSUE TITLE
Ducky scipt some commands not working

### ISSUE THREAD

**Issue by johnybravo3364** [michalmonday/supremeDuck#3]
hi found other commands not working in ducky script

"REPEAT" not working
"DELAY" not working
"DEFAULTDELAY" not working
"DEFAULT_DELAY" not working

**Comment by michalmonday** [comment]
Thanks again, I guess it was not a good idea to "fix things" at 3am...
I just updated the files (version 1.071)

**Comment by johnybravo3364** [comment]
fixed:
"REPEAT" working
"DELAY" working
"DEFAULTDELAY" working
"DEFAULT_DELAY" working

But "ALT" combinations corrupted again :(
when using combination with "ALT" key it send "^" key

**Comment by johnybravo3364** [comment]
also receiving low memory warning on arduino ide for supremeDuck.ino

Sketch uses 17690 bytes (61%) of program storage space. Maximum is 28672 bytes.
Global variables use 1966 bytes (76%) of dynamic memory, leaving 594 bytes for local variables. Maximum is 2560 bytes.
Low memory available, stability problems may occur.

**Comment by michalmonday** [comment]
My bad, after finishing with testing I just edited 1 line and didn't verify it, but it's all good now... (hopefully:p)

For the memory warning I'd just ignore it to be honest. If by any chance the device stops responding (e.g. communication with smartphone is not working) then it would be good to do something about it, but I didn't notice anything like that so far. 
There's 594 bytes for local variables but there's not much of local variables being used throughout the code, it's mostly the global variables that are used.

**Comment by johnybravo3364** [comment]
great testing now :)
thanks for all your work , its much apreciate

**Comment by johnybravo3364** [comment]
FIXED :) thank you

**Comment by johnybravo3364** [comment]
best wifi hid injector i tested.
v2 or any update planned ?

**Comment by michalmonday** [comment]
Good to hear that:) I'm out of ideas on how to improve it to be honest, one thing that I'd like to change is to ~~remove limit of 195 chars per line of ducky script.~~ (done)

I'm also trying to design a board like CJMCU Beetle that would be smaller and allow soldering Esp-12F to the back of it (without the need to use wires, just like "WHID" but a bit smaller). But that's more for me to learn about how to design circuit boards rather than developing this project.

If you like these kind of devices then there's the "WHID Elite" thing by Luca Bongiorni. I'm not sure how convenient it will be to use in practice but he progressed the "wireless hid injector" idea few steps forward.
https://twitter.com/hashtag/WHIDelite?src=hash&lang=en

**Comment by johnybravo3364** [comment]
i think your injector coding is more then complete , mouse control , keyboard layout change without unplug, multilanguage layout..... 

there is also hid injector inside usb cable , i think Kevin Mithnick made one, but he used some super tiny board i think .

**Comment by johnybravo3364** [comment]
Mousejacking maybe ?
something like :
https://github.com/insecurityofthings/uC_mousejack
https://github.com/insecurityofthings/jackit

**Comment by michalmonday** [comment]
Mousejacking is cool but:
1. It would require using NRF24L01 module and it can't directly communicate with mobile phone (correct me if I'm wrong) which means that it would have to be added to the build, it couldn't just replace HC-06 or Esp8266.
2. I think that the idea of adding mousejacking as a part of wireless HID device is a bit like this:
![image](https://upload.wikimedia.org/wikipedia/commons/a/a1/AntonovA40.jpg)
The wireless HID is meant to be plugged in the target machine, the NRF24L01 that does mousejacking does not have to be plugged in, it can be kept in your pocket, so it would be convenient to add suitable connectors/battery, whereas wireless HID should be as small as possible. Idea of merging these 2 concepts limits their attributes to some extent, just like the idea of flying tank instead of having tank and plane separately.

**Comment by johnybravo3364** [comment]
you are right.

maybe you can try to add keyboard layout detection ?

**Comment by michalmonday** [comment]
It would be cool but I have no idea how to do that. Even if I added some command to detect the keyboard language and pass it back to the device somehow, correctly inputting that command without knowing the layout in the first place would be not always possible.

I added some different features over the last week though, like OS detection, I also adapted the app to work on Linux and macOS

**Comment by johnybravo3364** [comment]
USB 3.0 support maybe ?

**Comment by michalmonday** [comment]
But it works well when plugged in to USB 3.0 port.
