### ISSUE TITLE
Wemos D1 mini ESP8266

### ISSUE THREAD

**Issue by ltiisidii** [michalmonday/supremeDuck#5]
I followed all the steps of the tutorial:

https://github.com/michalmonday/supremeDuck/wiki/How-to-make-wifi-based-version-(Esp8266)

I connect to "supremeDuck", turn off the data package of the phone, from the phone application I do "check connection". Until there it works, when I select for example Website, I choose a google preset, I execute the script and nothing happens.

I can not find what is wrong. In the application it shows: Sending ducky script (5 left) Last response time: HH: MM: SS P.M. and nothing happens.

This is my Board:
https://static.mercadoshops.com/mini-nodemcu-d1-wifi-esp8266-esp12f-4mb-uart-arduino-nubbeo_iZ549560322XsZ137430519XpZ1XfZ137430519-609363485-1XvZgrandexIM.jpg?v=20190411_153730

https://static.mercadoshops.com/mini-nodemcu-d1-wifi-esp8266-esp12f-4mb-uart-arduino-nubbeo_iZ549560322XvZgrandeXpZ3XfZ137430519-609363485-3XsZ137430519xIM.jpg
Sorry for my english

**Comment by michalmonday** [comment]
Hello, could you post picture (or few pictures) of wiring? Could you also tell the behavior of the blue LED of D1 mini just after connecting? That's how it should look if everything goes well:  
<img src="https://monday.pythonanywhere.com/img/LEDs_startup.gif" />  

The first long blink means the Esp-12F (D1 Mini) code is running, the 3 short blinks afterwards mean that is successfully communicated with the Atmega32U4 board (e.g. Arduino Pro Micro).  The green blink is the on-board LED of Atmega32U4 board which blinks after successfully communicating with the D1 Mini board.  

Btw make sure that the `//#define WIFI_DUCKY_SETUP` line is uncommented before uploading the code to Atmega32U4 based board

What you could additionally do is to uncomment this line in the supremeDuck.ino code:
```cpp
//#define WAIT_FOR_SERIAL_MONITOR_TO_OPEN
```
Uncommenting that line will make sure that the code stops after plugging in device, it will wait till you open "Arduino IDE -> Tools -> Serial Monitor" and automatically continue working. (In the right-bottom corner of the serial monitor window select 115200, you might have to close the window afterwards and replug the device and open serial monitor again). It should either print:
`Esp runs`
Or:
`Esp didn't respond, resetting.` - repeatedly

After `Esp didn't respond, resetting.` message the Atmega32U4 will attempt to reset the D1 Mini by pulling "EN" pin low for a moment (using A2 pin of Arduino Pro Micro) and try to communicate with it again.  

> In the application it shows: Sending ducky script (5 left) Last response time: HH: MM: SS P.M. and nothing happens.  

`Sending ducky script (5 left)` is normal message, but the fact that it doesn't count down towards 0 means lack of communication with the Atmega32U4 board. Most of the functions of the mobile application were redesigned to be activated by sending ducky script lines, after each line sent and executed by Atmega32U4, the Atmega32U4 should respond with "OK" and the next line should proceed to be sent. It doesn't happen so either:
- Atmega32U4 code doesn't run (or the `WIFI_DUCKY_SETUP` is not defined)
- RX/TX are not connected properly  
- initialisation of Esp routine is not working (where a handshake takes place between Atmega32U4 board and D1 Mini takes place) because A2-EN is not connected properly or because D1 Mini outputs some additional info through serial that interferes with the 'im_ok' handshake message (in such case the additional info would be visible in serial monitor)

**Comment by ltiisidii** [comment]
I am grateful for all the information you provide me, I am a newbie in this Arduino, I was reading all night to try to understand about the connections of the pins, voltages and others. I did not understand if it was necessary or not, to have the Atmega32U4 connected to the D1 mini. I will buy all the components of the image (only buy the d1 mini, thinking (badly) that it was enough)

The supremeDuck.ino send it to the D1 Mini. When you have the Atmega32U4 with me, I follow everything you told me.
Many, many thanks for the information.

**Comment by michalmonday** [comment]
Good to see that the problem was recognized.

<img src="https://raw.githubusercontent.com/michalmonday/files/master/supremeDuck/resources/repository%20stuff/wifi_guide_images/wifi_supremeDuck_with_switch_bb.png" width=400 />
(open image in new tab to enlarge)

If you use that image for reference then keep in mind that you will not need zener diodes if you're using D1 Mini board. D1 Mini already has built-in voltage regulator, so you can power it using its' 5V pin from the "RAW" pin of Arduino Pro Micro or equivalent Atmega32U4 based board (it also may be called 5V on "CJMCU Beetle" board for example).

Zener diodes or additional voltage regulator would be necessary only if you'd use plain Esp8266 board like Esp-12F for example (that requires 3.3V instead of 5V).

**Comment by ltiisidii** [comment]
One more question, D1 mini does not have ch_pd.
Pin A2 of the ATMEGA is connected with a cable to the D3 of the MINI D1?

<img src="https://i.imgur.com/eeV8S9j.png" alt="MINI D1 PinOUT" >

https://wiki.wemos.cc/products:d1:d1_mini

**Comment by michalmonday** [comment]
If you have the version of D1 mini with Esp-12F laying on top of it you can just solder the wire into the "EN" pin of Esp-12F. 

> Pin A2 of the ATMEGA is connected with a cable to the D3 of the MINI D1?  

A2 pin should be connected with "EN" pin of Esp-12F (which may be also called "CH_PD")

Pin 2 should be connected with GPIO 0 of Esp-12F (GPIO 0 is pin D3 of the Wemos D1 mini board)

Btw I have Wemos D1 mini board so I'll test connecting directly to Esp-12F and I'll update this message just to confirm it works.

**Comment by michalmonday** [comment]
It works well, you can see on the image below how A2 pin of Arduino Pro Micro is connected directly to the EN pin of Esp-12F (yellow wire) 
<img src="https://i.imgur.com/IGEDOS1.jpg" width=400 />

This image shows how D3 of Wemos is connected to pin 2 of Arduino Pro Micro (closest yellow wire)
<img src="https://i.imgur.com/sw7IJJ5.jpg" width=400 />

That's how it should look like when plugged in (1 second blink of blue led showing that the code is running, then 3 quick blinks showing that it successfully communicates with Arduino Pro Micro):  
https://i.imgur.com/nLHc0sp.mp4

(btw ignore the black transistors behind the Wemos on the images/gif, Wemos normally has them but they're much smaller, I just replaced mine with these big onese when I was working on something different)

**Comment by ltiisidii** [comment]
I'm going to buy the switch and test it 👍 

<img src="https://i.imgur.com/SJXlD8t.jpg" alt="build">

**Comment by ltiisidii** [comment]
**now it works!!**

<img src="https://i.imgur.com/3Y5RdWC.jpg" alt="ITS HAPPENING!!!">

**Comment by michalmonday** [comment]
Nice:) Btw the switch helps to reprogram Esp-12F through Atmega32U4 board but it's not necessary (especially that you're using D1 Mini which can be easily reprogrammed using its' USB connector)
