### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by dhoname** [michalmonday/supremeDuck#6]
hi! im trying to compile this project, but on the wiki there is not a word about the necessary libraries or about setting up an ide

I assumed that it was necessary to install the USBhost library, however, because of this, the output warns about the incompatibility of SAM and AVR and gives a trillion errors related to it
I also changed boards and ide versions but the result is the same

![image](https://user-images.githubusercontent.com/97642665/202776646-26f49b17-93d9-4157-8841-9cc7ba8d9674.png)

**Comment by michalmonday** [comment]
Hello, at the end of the output you posted it looks like the `source/supremeDuck` directory contains `MouseController.cpp`. That is very weird because in this repository the `source/supremeDuck` does not have such file. 

As far as I know all libraries supremeDuck code requires are either already provided in `source/supremeDuck` directory or come with standard Arduino IDE by default (e.g. `#include <Mouse.h>`) and do not need to be separately installed.

USBhost library is not needed, I'm not sure if it would interfere with compilation if it was installed (it would be weird if it did, I'd first try to find out why there's `MouseController.cpp` in the supremeDuck directory).

I would get a fresh copy of [source/supremeDuck](https://github.com/michalmonday/supremeDuck/tree/master/source/supremeDuck) and try to compile it again. If the problem persists, I'd uninstall/delete the USBhost library. I would assume that it replaces some header files with alternative one (e.g. if it replaces `HID.h` which is imported in the [Keyboard.h](https://github.com/michalmonday/supremeDuck/blob/master/source/supremeDuck/Keyboard.h), then it could be the reson of this issue).

**Comment by dhoname** [comment]
@michalmonday Yep, these files were to blame, I copied them because I received a compilation error due to the fact that the digispark board was selected
thanks for the help
